export const WEB_PUBLIC_ROUTES = [
  "/",
  "/privacy",
  "/terms",
  "/rules",
  "/rules/queue",
  "/rules/wallet",
  "/rules/activity/[slug]",
  "/delete-account",
  "/contact"
] as const;

export const MOBILE_INTERNAL_ROUTES = [
  "/(public)/welcome",
  "/(public)/auth/phone",
  "/(public)/auth/otp",
  "/(app)/(tabs)/home",
  "/(app)/(tabs)/queue",
  "/(app)/(tabs)/tasks",
  "/(app)/(tabs)/invites",
  "/(app)/(tabs)/wallet",
  "/(app)/(tabs)/me",
  "/(app)/product/[productId]",
  "/(app)/checkout/[productId]",
  "/(app)/orders/success/[orderId]",
  "/(app)/queue/[entryId]",
  "/(app)/wallet/withdraw",
  "/(app)/me/addresses",
  "/(app)/me/security",
  "/(app)/rules",
  "/(app)/rules/queue",
  "/(app)/rules/wallet",
  "/(app)/rules/activity/[campaignId]",
  "/(app)/privacy",
  "/(app)/terms",
  "/(app)/support",
  "/(app)/delete-account"
] as const;

export const ADMIN_ROUTES = [
  "/login",
  "/",
  "/products",
  "/products/[productId]",
  "/orders",
  "/orders/[orderId]",
  "/queues",
  "/queues/[entryId]",
  "/slots",
  "/slots/[slotId]",
  "/campaigns",
  "/campaigns/[campaignId]",
  "/tasks",
  "/tasks/[taskId]",
  "/invites",
  "/invites/[relationId]",
  "/wallet",
  "/withdrawals",
  "/risk",
  "/risk/[caseId]",
  "/governance",
  "/audit"
] as const;
