export enum OrderStatus {
  CREATED = 'CREATED',
  WAIT_PAY = 'WAIT_PAY',
  PAID = 'PAID',
  FULFILLING = 'FULFILLING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  AFTERSALE_OPEN = 'AFTERSALE_OPEN',
  PARTIAL_REFUNDED = 'PARTIAL_REFUNDED',
  FULL_REFUNDED = 'FULL_REFUNDED',
}
