export enum WithdrawalStatus {
  APPLIED = 'APPLIED',
  RISK_REVIEW = 'RISK_REVIEW',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}
